### ISSUE TITLE
How to insert external entity directly into the expression

### ISSUE THREAD

**Issue by DelvisR** [meatGUY/System.Linq.Dynamic#19]
The expression refers to an external entity to search for a value based on the field of the primary entity:

db.Table1.Select("new (it.Field1 as Table1F1, @0.FirstOrDefault(Fieldx == ^.Field1).Description as Table2F)", **db.Table2**)

Existe alguna forma de referenciar la entidad externa directamente en la cadena sin usar el parámetro:

db.Table1.Select("new (it.Field1 as Table1F1, **Table2**.FirstOrDefault(Fieldx == ^.Field1).Description as Table2F)")

Result of the execution: _No property or field 'Table2' exists in type 'Table1'_ 

Any suggestion?

Thank you,

Delvis

**Comment by ghost** [comment]
Hi @DelvisR,

The first expression:

```
db.Table1.Select("new (it.Field1 as Table1F1, @0.FirstOrDefault(Fieldx == ^.Field1).Description as Table2F)", db.Table2)
```

Should work, because this is the way you can reference **existing in memory object** in the query.

The seconds expressions doesn't work because `Table2` isn't unknown to the expression evaluator (as both as type and as object).

**Comment by ghost** [comment]
I am closing this issue because I haven't head from you for some time.
