### ISSUE TITLE
ExtentionMethod

### ISSUE THREAD

**Issue by gertcloete** [meatGUY/System.Linq.Dynamic#20]
I have written an implementation of IDynamicLinkCustomTypeProvider that load all my custom lynq functions:

When I use my DynamicLinqCustomTypeProvider I can use my Funcs.Left('asdfgh',3) fine as a expression, but unable to use 
Funcs.Left('asdfgh',3).Last()

Ie I am trying to make string extension methods that can be chained together. (Example below is just a simple one to show what I am trying to achieve) I have also noticed that GetExtensionMethods on DynamicLinqCustomTypeProvider  is never called, but GetCustomTypes is called. Can you please help?

`
 class DynamicLinqCustomTypeProvider : AbstractDynamicLinqCustomTypeProvider, IDynamicLinkCustomTypeProvider
{
public virtual HashSet<Type> GetCustomTypes() {...}
public Dictionary<Type, List<MethodInfo>> GetExtensionMethods() {...}
public Type ResolveType(string typeName) {...}
public Type ResolveTypeBySimpleName(string simpleTypeName) {...}
}

namespace Expressions
{
    [DynamicLinqType]
    public static class Funcs
    {
        public static string Left(object text, int numChars)
        {
            return Left(text as string, numChars);
        }
        public static string Last(this string input)
        {
            return input.Substring(str.Length - 1);
        }
    }
}
`

**Comment by ghost** [comment]
Hi @gertcloete,

I have checked the `IDynamicLinkCustomTypeProvider` interface and it doesn't have `GetExtensionMethods` method.

Here is a definition:

``` csharp
/// <summary>
/// Interface for providing custom types for Dynamic Linq.
/// </summary>
public interface IDynamicLinkCustomTypeProvider
{
  /// <summary>
  /// Returns a list of custom types that Dynamic Linq will understand.
  /// </summary>
  [Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate")]
  HashSet<Type> GetCustomTypes();
}
```

Regarding what you are trying to achieve - can you elaborate a bit more about why you need to implement this through extension methods instead of ordinary methods?

**Comment by gertcloete** [comment]
As far is my understanding go, this is the interface, which have a method for types and one for extension methods : GetExtensionMethods

`
using JetBrains.Annotations;
using System.Collections.Generic;
using System.Reflection;

namespace System.Linq.Dynamic.Core.CustomTypeProviders
{
    /// <summary>
    /// Interface for providing functionality to find custom types for or resolve any type.
    /// </summary>
    public interface IDynamicLinqCustomTypeProvider
    {
        /// <summary>
        /// Returns a list of custom types that System.Linq.Dynamic.Core will understand.
        /// </summary>
        /// <returns>A <see cref="HashSet{Type}" /> list of custom types.</returns>
        HashSet<Type> GetCustomTypes();

        /// <summary>
        /// Returns a list of custom extension methods that System.Linq.Dynamic.Core will understand.
        /// </summary>
        /// <returns>A list of custom extension methods that System.Linq.Dynamic.Core will understand.</returns>
        Dictionary<Type, List<MethodInfo>> GetExtensionMethods();

        /// <summary>
        /// Resolve any type by fullname which is registered in the current application domain.
        /// </summary>
        /// <param name="typeName">The typename to resolve.</param>
        /// <returns>A resolved <see cref="Type"/> or null when not found.</returns>
        Type ResolveType([NotNull] string typeName);

        /// <summary>
        /// Resolve any type by the simple name which is registered in the current application domain.
        /// </summary>
        /// <param name="simpleTypeName">The typename to resolve.</param>
        /// <returns>A resolved <see cref="Type"/> or null when not found.</returns>
        Type ResolveTypeBySimpleName([NotNull] string simpleTypeName);
    }
}
`

To explain the requirement, we are trying to use the dynamic lynq in the following scenario.
Below is the way it work currently, but the bottom example is how I would like to use it. Hence I would like to make extension methods evaluate also. IE I have an custom method: Funcs.Split(...) that return a string[] and then a extension custom method that work in string[] and can join then ie Funcs.TextJoin(...)

In practice we will not Split and join like the unit test below, as the extension method we want to make is more complicated. The below was just to proof out one can make extension methods, that can be used in the dynamic lynq parser.
`
 [Test]
        public async Task Expression_with_textleft_and_last()
        {
            dynamic row = new ExpandoObject();
            row.Address = "12 Church Street, Washington,United States";

            string returnValue = _expressionEvalutator.Evaluate<string>(row, "Funcs.TextJoin(\"|\", (Funcs.Split(\",\", Address)))");

            Assert.AreEqual("12 Church Street| Washington|United States", returnValue);
        }
`

`
 [Test]
        public async Task Expression_with_textsplit_on_comma_and_join_by_pipe_ext()
        {
            dynamic row = new ExpandoObject();
            row.Address = "12 Church Street, Washington,United States";

            string returnValue = _expressionEvalutator.Evaluate<string>(row, "Funcs.Split(\",\", Address).TextJoin(\"|\")");

            Assert.AreEqual("12 Church Street| Washington|United States", returnValue);
        }
`

**Comment by ghost** [comment]
@gertcloete,

I have noticed that you have mentioned `System.Linq.Dynamic.Core.CustomTypeProviders` namespace and that makes me feel like you are asking question in wrong repository because in this repo - there is no such namespace and `IDynamicLinkCustomTypeProvider` interface is exactly as I showed you in previous comment.

Regarding the use case you have described - I get it, it looks more natural, however, in current implementation of DynamicLinq this isn't possible.

**Comment by gertcloete** [comment]
I apologize, I needed to be here: https://github.com/zzzprojects/System.Linq.Dynamic.Core
